name = "gold-price-bot"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
GITHUB_REPO = "TranhGio/Danang-Gold-price"
GITHUB_BRANCH = "master"

[[kv_namespaces]]
binding = "BOT_STATE"
id = "e44aa30a6db14b6f9c61ad07b5d5e1d1"
